/**
 * services/starter-projects.ts
 *
 * Reads the bundled Squad-IRL starter projects from disk. The bundle is
 * generated by `scripts/generate-starters.mjs` and lives under
 * `src/data/starters/` (copied to `dist/data/starters/` at build time).
 *
 * Runtime is fully offline: no network, no rate limits, no TS evaluation.
 * Each starter is a folder with `meta.json`, `readme.md`, `plan.json`, and
 * `source.ts`. The catalogue manifest lives at `index.json`.
 *
 * Public API:
 *   listStarters()             → manifest entries (cached after first read)
 *   getStarter(slug)           → meta + readme + plan + source for one starter
 *   getStarterPlan(slug)       → just the plan (used by materialiser)
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import type { IrlProvisioningPlan } from './irl-mapper.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Resolve relative to this module's location so it works in both
// dev (src/services → src/data) and prod (dist/services → dist/data).
const STARTERS_DIR = path.resolve(__dirname, '..', 'data', 'starters');

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------
export interface StarterIndexEntry {
  slug: string;
  title: string;
  blurb: string;
  tags: string[];
  agentCount: number;
  routingRuleCount: number;
  ceremonyCount: number;
}

export interface StarterMeta extends StarterIndexEntry {
  defaultModel: string | null;
  teamName: string | null;
  warnings: string[];
  source: { origin: string; repo: string; ref: string };
  files: string[];
  htmlUrl: string;
  bundledAt: string;
}

export interface StarterDetail {
  meta: StarterMeta;
  readme: string;
  plan: IrlProvisioningPlan;
  source: string;
}

export interface StarterManifest {
  generatedAt: string;
  source: { origin: string; repo: string; ref: string };
  starters: StarterIndexEntry[];
}

// ---------------------------------------------------------------------------
// In-process cache (read-once, the bundle is immutable at runtime)
// ---------------------------------------------------------------------------
let manifestCache: StarterManifest | null = null;
const detailCache = new Map<string, StarterDetail>();

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------
export async function listStarters(): Promise<StarterIndexEntry[]> {
  const manifest = await loadManifest();
  return manifest.starters;
}

export async function getStarterManifest(): Promise<StarterManifest> {
  return loadManifest();
}

export async function getStarter(slug: string): Promise<StarterDetail | null> {
  if (!isValidSlug(slug)) return null;

  const cached = detailCache.get(slug);
  if (cached) return cached;

  const manifest = await loadManifest();
  if (!manifest.starters.find((s) => s.slug === slug)) return null;

  const dir = path.join(STARTERS_DIR, slug);
  let meta: StarterMeta;
  let readme: string;
  let plan: IrlProvisioningPlan;
  let source: string;
  try {
    [meta, readme, plan, source] = await Promise.all([
      fs.readFile(path.join(dir, 'meta.json'), 'utf-8').then(JSON.parse) as Promise<StarterMeta>,
      fs.readFile(path.join(dir, 'readme.md'), 'utf-8').catch(() => ''),
      fs.readFile(path.join(dir, 'plan.json'), 'utf-8').then(JSON.parse) as Promise<IrlProvisioningPlan>,
      fs.readFile(path.join(dir, 'source.ts'), 'utf-8').catch(() => ''),
    ]);
  } catch (err) {
    throw new Error(`Failed to read starter "${slug}": ${(err as Error).message}`);
  }

  const detail: StarterDetail = { meta, readme, plan, source };
  detailCache.set(slug, detail);
  return detail;
}

export async function getStarterPlan(slug: string): Promise<IrlProvisioningPlan | null> {
  const detail = await getStarter(slug);
  return detail?.plan ?? null;
}

/** Test-only: clear caches. */
export function _resetStarterCacheForTests(): void {
  manifestCache = null;
  detailCache.clear();
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
async function loadManifest(): Promise<StarterManifest> {
  if (manifestCache) return manifestCache;

  const indexPath = path.join(STARTERS_DIR, 'index.json');
  try {
    const raw = await fs.readFile(indexPath, 'utf-8');
    manifestCache = JSON.parse(raw) as StarterManifest;
    return manifestCache;
  } catch (err) {
    throw new Error(
      `Starter project bundle not found at ${indexPath}. ` +
        `Run \`pnpm --filter @sabbour/squadboard-server gen:starters\` to generate. ` +
        `Underlying error: ${(err as Error).message}`,
    );
  }
}

function isValidSlug(slug: string): boolean {
  return /^[a-z0-9][a-z0-9._-]{0,80}$/i.test(slug);
}
